package RDBAC.model.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import RDBAC.model.Client;
import RDBAC.model.Item;
import RDBAC.model.User;

/**
 * Class _Order was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Order extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CLIENT = Property.create("client", String.class);
    public static final Property<LocalDateTime> DATE = Property.create("date", LocalDateTime.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<Client> CLIENT1 = Property.create("client1", Client.class);
    public static final Property<Item> ITEM = Property.create("item", Item.class);
    public static final Property<User> USER = Property.create("user", User.class);

    public void setClient(String client) {
        writeProperty("client", client);
    }
    public String getClient() {
        return (String)readProperty("client");
    }

    public void setDate(LocalDateTime date) {
        writeProperty("date", date);
    }
    public LocalDateTime getDate() {
        return (LocalDateTime)readProperty("date");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setClient1(Client client1) {
        setToOneTarget("client1", client1, true);
    }

    public Client getClient1() {
        return (Client)readProperty("client1");
    }


    public void setItem(Item item) {
        setToOneTarget("item", item, true);
    }

    public Item getItem() {
        return (Item)readProperty("item");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
